// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkmyobxdztspftuamiyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbXlvYnhkenRzcGZ0dWFtaXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDUzNTUsImV4cCI6MjA2MzcyMTM1NX0.b9bs4DGO_TOS3NjRKLenDLN_m3N0Ath54EZZ68BP1FA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);